AllCops:
  TargetRubyVersion:
    2.4
  DisplayCopNames: true
  # DisabledByDefault: true
  Exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - db/migrate/*
    - db/default/*
    - config/initializers/*
    - config/environments/*
    - bin/*
    - spec/*/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - test/*
    - config.ru
    - Rakefile

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Enabled: false

Style/AsciiIdentifiers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/BlockDelimiters:
  Enabled: false

StringLiterals:
  Enabled: false

Style/AlignParameters:
  Enabled: false
