default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ske_rails_development

test:
  <<: *default
  database: ske_rails_test

default: &default_settings
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

staging:
  <<: *default
  <<: *default_settings

production:
  <<: *default
  <<: *default_settings
